name: TorchFire
version: ${project.version}
main: me.aaronlyy.torchfire.main.Main
api-version: 1.13
authors: [aaronlyy]
description: This plugin sets burnable blocks on fire if they are placed above a torch
